const FETCH_THUNK_DATA_REQUEST = 'FETCH_THUNK_DATA_REQUEST'
const FETCH_THUNK_DATA_SUCCESS = 'FETCH_THUNK_DATA_SUCCESS'
const FETCH_THUNK_DATA_FAILURE = 'FETCH_THUNK_DATA_FAILURE'

export {
  FETCH_THUNK_DATA_REQUEST,
  FETCH_THUNK_DATA_SUCCESS,
  FETCH_THUNK_DATA_FAILURE
}
