const FETCH_EPIC_SHOW_LOADING = 'FETCH_EPIC_SHOW_LOADING'
const FETCH_EPIC_HIDE_LOADING = 'FETCH_EPIC_HIDE_LOADING'
const FETCH_EPIC_DATA_REQUEST = 'FETCH_EPIC_DATA_REQUEST'
const FETCH_EPIC_KILL_REQUEST = 'FETCH_EPIC_KILL_REQUEST'
const FETCH_EPIC_DATA_SUCCESS = 'FETCH_EPIC_DATA_SUCCESS'
const FETCH_EPIC_DATA_FAILURE = 'FETCH_EPIC_DATA_FAILURE'

export {
  FETCH_EPIC_SHOW_LOADING,
  FETCH_EPIC_HIDE_LOADING,
  FETCH_EPIC_DATA_REQUEST,
  FETCH_EPIC_KILL_REQUEST,
  FETCH_EPIC_DATA_SUCCESS,
  FETCH_EPIC_DATA_FAILURE,
}
