const FETCH_EPIC_DATA_REQUEST = 'FETCH_EPIC_DATA_REQUEST'
const FETCH_EPIC_DATA_SUCCESS = 'FETCH_EPIC_DATA_SUCCESS'
const FETCH_EPIC_DATA_FAILURE = 'FETCH_EPIC_DATA_FAILURE'

export {
  FETCH_EPIC_DATA_REQUEST,
  FETCH_EPIC_DATA_SUCCESS,
  FETCH_EPIC_DATA_FAILURE
}
