const FETCH_SAGA_DATA_REQUEST = 'FETCH_SAGA_DATA_REQUEST'
const FETCH_SAGA_DATA_SUCCESS = 'FETCH_SAGA_DATA_SUCCESS'
const FETCH_SAGA_DATA_FAILURE = 'FETCH_SAGA_DATA_FAILURE'

export {
  FETCH_SAGA_DATA_REQUEST,
  FETCH_SAGA_DATA_SUCCESS,
  FETCH_SAGA_DATA_FAILURE
}
