const FETCH_PROMISE_DATA_REQUEST = 'FETCH_PROMISE_DATA_REQUEST'
const FETCH_PROMISE_DATA_SUCCESS = 'FETCH_PROMISE_DATA_SUCCESS'
const FETCH_PROMISE_DATA_FAILURE = 'FETCH_PROMISE_DATA_FAILURE'

export {
  FETCH_PROMISE_DATA_REQUEST,
  FETCH_PROMISE_DATA_SUCCESS,
  FETCH_PROMISE_DATA_FAILURE
}
